<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>toeicspace-assessment-local</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ToeicSpace.Assessment.Application\ToeicSpace.Assessment.Application.csproj" />
    <ProjectReference Include="..\ToeicSpace.Assessment.Infrastructure\ToeicSpace.Assessment.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\ToeicSpace.BuildingBlocks.Security\ToeicSpace.BuildingBlocks.Security.csproj" />
  </ItemGroup>

</Project>
